#!/bin/bash
# Setup script for creating the Claude ecosystem repositories

echo "🚀 Setting up Claude ecosystem repositories..."
echo ""
echo "This script will help you create the three related repositories:"
echo "1. claude-ultrathink"
echo "2. claude-am" 
echo "3. claude-contexify"
echo ""
echo "The template files are in _project_templates/"
echo ""
echo "To create each repository:"
echo ""
echo "# For claude-ultrathink:"
echo "cd .. && cp -r claude-ecosystem/_project_templates/claude-ultrathink . && cd claude-ultrathink"
echo "git init"
echo "git add ."
echo 'git commit -m "Initial commit: Claude-UltraThink single-agent methodology"'
echo "gh repo create claude-ultrathink --public --source=. --remote=origin --push"
echo ""
echo "# For claude-am:"
echo "cd .. && cp -r claude-ecosystem/_project_templates/claude-am . && cd claude-am"
echo "git init"
echo "git add ."
echo 'git commit -m "Initial commit: Claude-AM multi-agent orchestration system"'
echo "gh repo create claude-am --public --source=. --remote=origin --push"
echo ""
echo "# For claude-contexify:"
echo "cd .. && cp -r claude-ecosystem/_project_templates/claude-contexify . && cd claude-contexify"
echo "git init" 
echo "git add ."
echo 'git commit -m "Initial commit: Claude-Contexify context optimization strategies"'
echo "gh repo create claude-contexify --public --source=. --remote=origin --push"
echo ""
echo "After creating the repositories, update claude-ecosystem README.md to remove '(coming soon)' from the links."